name: reactive_text_form
description: Displays error messages in a reactive manner, which is not currently possible with the existing Text form. This package enables users to receive error messages more efficiently.
version: 0.0.3
homepage: https://github.com/kumarsiddy/reactive_text_form.git

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.3

flutter:
